### ISSUE TITLE
attack-severity refienement

### ISSUE THREAD

**Issue by ioggstream** [tireddy2/ohai#13]
## I expect

attack-severity to have one of the severity values in this IANA registry https://www.iana.org/assignments/iodef2/iodef2.xhtml

## Instead

is a sf-integer

**Comment by tireddy2** [comment]
Good catch, please replace with sf-string.

**Comment by ioggstream** [comment]
@tireddy2 do you think attack-severity should be ohai specific or we could leave it open to use for other specs?

**Comment by tireddy2** [comment]
attack-severity looks specific to an trusted intermediary (e.g., oblivious proxy). I don't see any benefit sending it to misbehaving clients. Further, it could reveal to an malicious client about the impact of the attack.
