### ISSUE TITLE
Markdown template

### ISSUE THREAD

**Issue by ioggstream** [tireddy2/ohai#5]
## Question

- there's a github repository template for RFC, e.g. https://github.com/ietf-wg-httpapi/mediatypes that generates xml and github pages from markdown, and supports automatic posting to datatracker. Do you want to give it a try? It will allow you to write RFC faster.

**Comment by tireddy2** [comment]
We use xml as source (see https://github.com/tireddy2/ohai/blob/main/draft-rdb-ohai-feedback-to-proxy-02.xml) and XMLmind XML Editor to update the draft.
