### ISSUE TITLE
oblivious-target syntax

### ISSUE THREAD

**Issue by ioggstream** [tireddy2/ohai#9]
## I expect

- to define the oblivious target syntax (sf-integer, sf-string, ...) 

## Instead

it is specified the generic syntax `sf-item` with some values, e.g.  `0x01`. It is not clear whether it's a binary, integer or string value.

**Comment by tireddy2** [comment]
It is an integer value.

**Comment by tireddy2** [comment]
I don't get the need to include sf-string in the oblivious target syntax.
